valores = input().split()
a = int(valores[0])
b = int(valores[1])
c = int(valores[2])
if a > b:
    if c > b:
        if c > a:
            print(b)
            print(a)
            print(c)
            print()
            print(a)
            print(b)
            print(c)
        else:
            print(b)
            print(c)
            print(a)
            print()
            print(a)
            print(b)
            print(c)
    else:
        print(c)
        print(b)
        print(a)
        print()
        print(a)
        print(b)
        print(c)
elif a > c:
    print(c)
    print(a)
    print(b)
    print()
    print(a)
    print(b)
    print(c)
elif c > b:
    print(a)
    print(b)
    print(c)
    print()
    print(a)
    print(b)
    print(c)
else:
    print(a)
    print(c)
    print(b)
    print()
    print(a)
    print(b)
    print(c)